version: '3'

services:
  mysqldb:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shapes_db
    volumes:
      - /data/mysql
    networks:
      - shapes-mysql
    ports:
      - 3306:3306
  shapes-app:
    image: spring-boot-jpa-image
    networks:
      - shapes-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "mysqldb:3306", "--timeout=120", "--", "java", "-jar", "app.jar"]
    ports:
      - 8080:8080
    volumes:
      - /data/shapes-service
networks:
    shapes-mysql:
